name: Test and lint
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Run tests and lint
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x

      - name: Test
        run: |
          make test

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.2
          args: --timeout=5m
