name: Test and lint
on:
  push:
    branches-ignore:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-24.04
    steps:
      - name: Setup Go Environment
        uses: ./.github/workflows/setup-go.yml

      - name: Test
        run: |
          make test

  lint:
    name: Run linter
    runs-on: ubuntu-24.04
    steps:
      - name: Setup Go Environment
        uses: ./.github/workflows/setup-go.yml

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.2
          args: --timeout=5m